# Generated by Django 3.1.7 on 2021-05-06 12:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_bid_category_comment_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='watchlist_users',
            field=models.ManyToManyField(blank=True, null=True, related_name='watch_list', to=settings.AUTH_USER_MODEL),
        ),
    ]
