# Generated by Django 3.1.7 on 2021-05-08 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_auto_20210507_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='created',
            field=models.CharField(default='05-08-2021, 12:27:29', max_length=30),
        ),
    ]
