# Generated by Django 3.1.7 on 2021-05-08 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_auto_20210508_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='created',
            field=models.CharField(default='05-08-2021, 18:13:20', max_length=30),
        ),
    ]
